[dump_create_config]
feed_dump_url = https://media_source.com/internal.php?page=adtools&category=3&typeid=23&view=dump
feed_set_url = https://media_source.com/internal.php?page=adtools&category=3&typeid=4

[feed_alpha]
feed_alpha_campaign_id = 1291575419

[feed_betas]
source_id = 576422190

[feed_delta_api]
# Found in the dump data like "utm_campaign=xx.xxx"
feed_delta_camp_utm = ai.FmY