"""
PostWizard - Secrets Manager view

This module defines the Gradio interface for managing secrets for various platforms and services.
It allows users to input their credentials and interact with the backend to store or remove them.

Author: Yoham Gabriel Urbine@GitHub
Email: yohamg@programmer.net
"""

__author__ = "Yoham Gabriel Urbine@GitHub"
__author_email__ = "yohamg@programmer.net"

import logging
import os
from pathlib import Path

# Third-party imports
import gradio as gr

from core.controllers.secrets_controller import (
    wp_remove_secrets,
    wp_update_secrets,
    google_remove_secrets,
    google_update_secrets,
    brave_remove_secrets,
    brave_update_secrets,
    telegram_remove_secrets,
    telegram_update_secrets,
    monger_cash_update_credentials,
    monger_cash_remove_credentials,
    x_remove_api_secrets,
    x_update_api_secrets,
    x_remove_credentials,
    x_update_credentials,
    x_client_update_secrets,
    x_client_remove_secrets,
    pw_api_update_credentials,
    pw_api_remove_credentials,
)

# Local imports
from core.views.themes import elegant_theme
from core.utils.file_system import logging_setup

with gr.Blocks(
    theme=elegant_theme, title="PostWizard - Secrets Manager"
) as secret_mgr_view:
    gr.Markdown("# PostWizard - Secrets Manager")
    with gr.Row():
        with gr.Column():
            with gr.Tab("WordPress"):
                wp_hostname = gr.Textbox(
                    label="WordPress Hostname", info="Your domain, e.g. example.com"
                )
                wp_username = gr.Textbox(
                    label="WordPress Author Username",
                    info="The username of the author of the blog",
                )
                wp_password = gr.Textbox(
                    label="WordPress Application Password",
                    type="password",
                    info="The application password for the blog. This is generated by you on the blog's admin panel.",
                )

                update_wp_secrets = gr.Button("Update WP Secrets")
                update_wp_secrets.click(
                    fn=wp_update_secrets,
                    inputs=[wp_hostname, wp_password, wp_username],
                    outputs=[],
                )

                delete_wp_secrets = gr.Button("Delete WP Secrets")
                delete_wp_secrets.click(
                    fn=wp_remove_secrets, inputs=[wp_hostname], outputs=[]
                )

            with gr.Tab("Google Search"):
                google_cse_id = gr.Textbox(
                    label="Google CSE ID",
                    info="The Custom Search Engine ID for the Google Custom Search API",
                )
                google_api_key = gr.Textbox(
                    label="Google API Key",
                    type="password",
                    info="The API key generated for the Google Custom Search API",
                )

                update_google_secrets = gr.Button("Update Google Secrets")
                update_google_secrets.click(
                    fn=google_update_secrets,
                    inputs=[google_api_key, google_cse_id],
                    outputs=[],
                )

                delete_google_secrets = gr.Button("Delete Google Secrets")
                delete_google_secrets.click(
                    fn=google_remove_secrets, inputs=[], outputs=[]
                )

            with gr.Tab("Brave Search"):
                brave_api_key = gr.Textbox(
                    label="Brave API Key",
                    type="password",
                    info="The API key generated for the Brave Search API",
                )

                update_brave_secrets = gr.Button("Update Brave Secrets")
                update_brave_secrets.click(
                    fn=brave_update_secrets, inputs=[brave_api_key], outputs=[]
                )

                delete_brave_secrets = gr.Button("Delete Brave Secrets")
                delete_brave_secrets.click(
                    fn=brave_remove_secrets, inputs=[], outputs=[]
                )

            with gr.Tab("Telegram"):
                telegram_chat_id = gr.Textbox(
                    label="Telegram Chat ID",
                    info="The Telegram chat ID for the BotFather service",
                )
                telegram_token = gr.Textbox(
                    label="Telegram Token",
                    type="password",
                    info="The token you generated for the BotFather service",
                )

                update_telegram_secrets = gr.Button("Update Telegram Secrets")
                update_telegram_secrets.click(
                    fn=telegram_update_secrets,
                    inputs=[telegram_chat_id, telegram_token],
                    outputs=[],
                )

                delete_telegram_secrets = gr.Button("Delete Telegram Secrets")
                delete_telegram_secrets.click(
                    fn=telegram_remove_secrets, inputs=[telegram_chat_id], outputs=[]
                )

            with gr.Tab("X (Twitter)"):
                gr.Markdown("## X Credentials")
                # Non-visible session username box to populate the secrets database and identify the system user.
                session_username_box = gr.Textbox(value="postwizard", visible=False)
                x_username = gr.Textbox(
                    label="X Username",
                    info="The username for your X account, e.g. @postwizard",
                )
                x_email = gr.Textbox(
                    label="X Email Address",
                    type="email",
                    info="The email address connected to your X account",
                )
                x_password = gr.Textbox(
                    label="X Password",
                    type="password",
                    info="The password for the X account",
                )

                update_x_credentials = gr.Button("Update X Credentials")
                update_x_credentials.click(
                    fn=x_update_credentials,
                    inputs=[x_username, x_email, x_password],
                    outputs=[],
                )

                delete_x_credentials = gr.Button("Delete X Credentials")
                delete_x_credentials.click(
                    fn=x_remove_credentials, inputs=[], outputs=[]
                )

                gr.Markdown("## X API Secrets (X Developer Portal)")
                x_api_key = gr.Textbox(
                    label="X API Key",
                    type="password",
                    info="The API key generated in X",
                )
                x_api_secret = gr.Textbox(
                    label="X API Secret",
                    type="password",
                    info="The API secret generated in X",
                )

                update_x_api_secrets = gr.Button("Update X API Secrets")
                update_x_api_secrets.click(
                    fn=x_update_api_secrets,
                    inputs=[session_username_box, x_api_key, x_api_secret],
                    outputs=[],
                )

                delete_x_api_secrets = gr.Button("Delete X API Secrets")
                delete_x_api_secrets.click(
                    fn=x_remove_api_secrets, inputs=[], outputs=[]
                )

                gr.Markdown("## X Client Secrets (X Developer Portal)")
                x_client_id = gr.Textbox(
                    label="X Client ID", info="The client ID generated in X"
                )
                x_client_secret = gr.Textbox(
                    label="X Client Secret",
                    type="password",
                    info="The client secret generated in X",
                )

                update_x_client_secrets = gr.Button("Update X Client Secrets")
                update_x_client_secrets.click(
                    fn=x_client_update_secrets,
                    inputs=[session_username_box, x_client_id, x_client_secret],
                    outputs=[],
                )

                delete_x_client_secrets = gr.Button("Delete X Client Secrets")
                delete_x_client_secrets.click(
                    fn=x_client_remove_secrets, inputs=[], outputs=[]
                )
            with gr.Tab("Content Providers"):
                gr.Markdown("## MongerCash")
                mcash_username = gr.Textbox(
                    label="Username",
                    info="The username for your MongerCash Affiliate Account",
                )
                mcash_password = gr.Textbox(
                    label="Password",
                    info="The password for your MongerCash Affiliate Account",
                    type="password",
                )

                store_mcash_secrets = gr.Button("Store MongerCash Credentials")
                store_mcash_secrets.click(
                    fn=monger_cash_update_credentials,
                    inputs=[mcash_username, mcash_password],
                    outputs=[],
                )

                delete_mcash_secrets = gr.Button("Delete MongerCash Credentials")
                delete_mcash_secrets.click(
                    fn=monger_cash_remove_credentials, inputs=[], outputs=[]
                )
            with gr.Tab("PostWizard API"):
                pw_api_username = gr.Textbox(
                    label="PostWizard API Username",
                    info="The username for your PostWizard API account",
                )
                pw_api_password = gr.Textbox(
                    label="PostWizard API Password",
                    type="password",
                    info="The password for your PostWizard API account",
                )

                update_pw_api_credentials = gr.Button(
                    "Update PostWizard API Credentials"
                )
                update_pw_api_credentials.click(
                    fn=pw_api_update_credentials,
                    inputs=[pw_api_username, pw_api_password],
                    outputs=[],
                )

                delete_pw_api_credentials = gr.Button(
                    "Delete PostWizard API Credentials"
                )
                delete_pw_api_credentials.click(
                    fn=pw_api_remove_credentials, inputs=[], outputs=[]
                )


if __name__ == "__main__":
    try:
        # Environment variable set in the ``logging_setup()`` function in the helpers.py file.
        logging_path = os.path.join(Path(__file__).parent.parent, "logs")
        logging_setup(logging_path, __file__)
        print("Starting Secret Manager...")
        print(f"Logging path at: {os.path.abspath(logging_path)}")
        secret_mgr_view.launch(server_port=9090, show_api=False)
    finally:
        logging.shutdown()
