from core.utils.decorators import singleton
from core.config.config_factories import (
    ai_config_factory,
    general_config_factory,
    image_config_factory,
    social_config_factory,
)

from core.exceptions.data_access_exceptions import (
    InvalidDB,
    InvalidSQLConfig,
    UnableToConnectError,
)
from core.exceptions.config_exceptions import (
    SectionsNotFoundError,
    ClientSecretsNotFound,
    InvalidAIConfig,
)
from core.exceptions.util_exceptions import (
    NoSuitableArgument,
    InvalidInput,
    UnsupportedParameter,
    UnavailableLoggingDirectory,
    UnsupportedPlatform,
    InvalidOperationMode,
)

from core.utils.helpers import (
    access_url,
    access_url_bs4,
    apply_os_permissions,
    clean_console,
    clean_file_cache,
    clean_filename,
    create_store,
    export_request_json,
    fetch_data_sql,
    filename_creation_helper,
    filename_select,
    generate_random_str,
    get_dict_key,
    get_duration,
    get_token_oauth,
    get_webdriver,
    goto_project_root,
    is_parent_dir_required,
    load_file_path,
    load_from_file,
    load_json_ctx,
    logging_setup,
    lst_dict_to_csv,
    match_list_elem_date,
    match_list_mult,
    match_list_single,
    parse_client_config,
    parse_date_to_iso,
    remove_if_exists,
    search_files_by_ext,
    sha256_hash_generate,
    split_char,
    str_encode_b64,
    write_to_file,
)

__all__ = [
    "ai_config_factory",
    "apply_os_permissions",
    "clean_console",
    "clean_file_cache",
    "clean_filename",
    "create_store",
    "export_request_json",
    "fetch_data_sql",
    "filename_creation_helper",
    "filename_select",
    "general_config_factory",
    "generate_random_str",
    "get_dict_key",
    "get_duration",
    "get_token_oauth",
    "get_webdriver",
    "goto_project_root",
    "image_config_factory",
    "is_parent_dir_required",
    "load_file_path",
    "load_from_file",
    "load_json_ctx",
    "logging_setup",
    "lst_dict_to_csv",
    "match_list_elem_date",
    "match_list_mult",
    "match_list_single",
    "parse_client_config",
    "parse_date_to_iso",
    "remove_if_exists",
    "search_files_by_ext",
    "sha256_hash_generate",
    "social_config_factory",
    "split_char",
    "str_encode_b64",
    "write_to_file",
    "access_url",
    "access_url_bs4",
]
